# Generated by Django 5.2.4 on 2025-09-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
