# Generated by Django 5.2.4 on 2025-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('roligion', models.CharField(choices=[('muslim', 'Muslim'), ('christian', 'Christian')], default='muslim', max_length=40)),
                ('cv', models.FileField(upload_to='cvs')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
