# Generated by Django 5.2.4 on 2025-09-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='roligion',
        ),
        migrations.AddField(
            model_name='post',
            name='religion',
            field=models.CharField(choices=[('muslim', 'Muslim'), ('christian', 'Christian')], default='muslim', max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
