# Generated by Django 5.2.4 on 2025-09-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_post_roligion_post_religion_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='has_exp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
