# Generated by Django 5.2.6 on 2025-09-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_post_gender_post_has_exp_post_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo'),
        ),
    ]
