# Generated by Django 5.2.6 on 2025-09-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
