# Generated by Django 5.2.6 on 2025-09-17 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_post_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='taken_posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_by_clients', to='job.post')),
            ],
            options={
                'ordering': ['-taken_at'],
                'unique_together': {('client', 'post')},
            },
        ),
    ]
