# Generated by Django 5.2.6 on 2025-10-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='archives/%Y/%m/%d/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
